# Code Climate Configuration
#
# @see https://codeclimate.com/
engines:
    phpcodesniffer:
        enabled: true
        config:
            file_extensions: php
            standard: PSR1
ratings:
    paths:
        - src/**
        - test/**
exlude_paths:
    - var
    - vendor
